import step1 from "./step-1.json";
import step2 from "./step-2.json";
import step3 from "./step-3.json";
import step4 from "./step-4.json";
import step5 from "./step-5.json";
import step6 from "./step-6.json";
import success from "./success.json";

/** A Lottie document; `op` is the last frame, used to park reduced-motion readers on the finished icon. */
export type LottieData = { readonly op: number } & Record<string, unknown>;

/** Process step icons keyed by step number. Generated by scripts/make-lottie.mjs. */
export const stepAnimations: Readonly<Record<number, LottieData>> = {
  1: step1,
  2: step2,
  3: step3,
  4: step4,
  5: step5,
  6: step6,
};

export const successAnimation: LottieData = success;
